export {default as Login } from './Login'
export {default as Register } from './Register'
export {default as Homepage } from './HomePage/Homepage'
export {default as Dashboard } from './pages/Dashboard/Dashboard'
export {default as Calendar } from './pages/Calendar/Calendar'
export {default as Jobs } from './pages/Jobs'
export {default as Layout } from './layout/Layout'
export {default as Profile } from './pages/Profile'
export {default as AddJob } from './pages/AddJob'
export {default as Header } from './layout/Header'
export { ProtectedRoute } from './ProtectedRoute'

